### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by YunisDEV** [theboolean/visitor-info#20]
i am using this package on node js app. But when i require package, is gives this error

/home/yunisdev/Documents/Programming/Web/happyhome/node_modules/visitor-info/dist/bundle.cjs.js:76
  return results || new UAParser(navigator.userAgent).getResult();
                                 ^

ReferenceError: navigator is not defined
    at getResult (/home/yunisdev/Documents/Programming/Web/happyhome/node_modules/visitor-info/dist/bundle.cjs.js:76:34)
    at Object.<anonymous> (/home/yunisdev/Documents/Programming/Web/happyhome/node_modules/visitor-info/dist/bundle.cjs.js:82:11)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/yunisdev/Documents/Programming/Web/happyhome/src/index.js:14:21)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by theboolean** [comment]
Hi @YunisDEV, thank you for your report. This library was conceived to be used in a web browser environment. What is your use case with NodeJS?

**Comment by YunisDEV** [comment]
How I can use it on browser

**Comment by theboolean** [comment]
You can find info on how to use it in the README
